#主配置文件
#环境变量设置,dev/uat/com等不同的环境变量设置
 db:
   dbname: "autotask"
   dbhost: "10.68.3.102"
   dbuser: "public"
   dbpassword: "public"
   dbport: "3306"
   apitable: "pre_host_zzb"
 env:
   key: "dev"
 uat: 
   #认证相关配置
   # key_auth=true时,为秘钥认证,pass_auth=true,为密码认证。秘钥认证和密码认证不能同时为真;
   # 当key_auth=true时,仅支持秘钥认证为空的情况
   # user:用户名 password:密码 private_key:私钥文件 public_key:公钥文件 global_sudo:是否开启sudo,on为开启,off为关闭 sudo_password:sudo时密码
   # logfile:日志文件 
   # groups_file:IP分组文件  
   # timeout:SSH超时时间  
   # max_connect_retries:SSH失败时最大连接尝试次数 
   # parallelism:使用分组时,最大的并发数量  
   # table:主机信息表(废弃)  
   # monitor_table:监控数据表(暂时不使用)  
   # rerite_info_table:是否写入json文件(暂时不使用)  
   # default_jsonfile:默认json串存储文件(暂时不使用)    
   # table_string:数据库初始化主机信息要查询的字段(不要轻易修改)  
   # softdir:待发布应用目录 
   # configuredir:待发布配置目录  
   # local_prodir:远程同步应用目录  
   # local_confdir:远程同步配置目录  
   # temp:应用发布时临时目录   
   # backup_dir:发布应用时,当数据库字段中backupdir_same_level为0时,且当配置目录在应用目录时,备份该应用程序的所在目录
   # baseapp_dir:发布应用时,当数据库字段中deploydir_same_level为0时,即是待发布目录的目录(发布目录不能和发布目录同层级),比如你的应用在webapp下,你的新的发布应用时不能再webapp下面,因为当你放在webapp下面时就相当于会启动2个app,所以需要另外的发布目录
   # download_all:是否下载所有的目录(暂时不使用,不能为空)  
   # is_link: 是否是软链接(暂时不使用,不能为空)  
   # is_stop:是否停止应用 (暂时不使用,不能为空)  
   # is_start:是否启动应用(暂时不使用,不能为空)  
   # download_record_log:下载应用的日志记录  
   # deploy_config_table:主机详细配置文件数据表(重要)  
   # deploy_record_table:发布时记录数据表 
   # deploy_status_table:发布时状态数据表  
   # external_status:是否开启外网表,当开启外网表时,需要你将新建 复制主机详细配置文件数据表,同时将内网地址和外网地址交换,当external_status为true时,deploy_config_table将不起作用,读取外网表
   # external_deploy_config_table:  主机详细配置文件数据表(外网表)
   # list_all_task_status:是否要打印所有的模块信息,如果不为false,则答应所有的模块信息。为false时,则打印list_task所列出的模块
   # list_task:执行rex -T 要显示的模块  
   # service_start_retry:启动服务失败时的尝试次数  
   # rsync_log_stdout:是否显示传输包的进度和传输速度
   key_auth: "true" 
   pass_auth: "false"  
   user: "baowang"
   password: ""
   private_key: "keys/baowang"
   public_key: "keys/baowang.pub"
   global_sudo: "on"
   sudo_password: "baowang2015"          
   logfile: "logs/rex.log"
   groups_file: "true,config/ip_lists.ini"
   timeout: "10"
   max_connect_retries: "8"
   parallelism: "5"
   table: "pre_host_zzb_dev"
   monitor_table: "pre_bwzzbmonitor_dev"
   rerite_info_table: "false"
   default_jsonfile: "cache/json/json.txt"
   table_string: "id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir"
   softdir: "softdir/"
   configuredir: "configuredir/"
   local_prodir: "remotecomdir/softdir/"
   local_confdir: "remotecomdir/configuredir/"
   temp: "temp/"
   download_dir: "download/"
   log_rsync_server: "172.16.0.244"
   log_rsync_user: "logupload"
   log_rsync_pass: "cm12016"
   log_rsync_module: "logupload"
   backup_dir: "/data/backup"
   baseapp_dir: "/data/www/apps"
   download_all : "false"
   is_link :  "true"
   is_stop :  "false"
   is_start :  "true"
   download_record_log: "logs/download_record.log"
   deploy_config_table: "pre_server_detail"
   deploy_record_table: "pre_deploy_manage"
   deploy_status_table: "pre_deploy_status"
   external_status: "true"
   external_deploy_config_table: "pre_external_server_detail"
   list_all_task_status: "false"
   list_task: "check,list,run,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Deploy:Db:initdb,Deploy:Core:syncpro,Common:Use:download,Common:Use:run,Common:Use:upload"
   service_start_retry: "5"
   rsync_log_stdout: "false"
#开发环境配置文件
 dev:
   key_auth: "true"
   pass_auth: "false"  
   user: "baowang"
   password: ""
   private_key: "keys/baowang"
   public_key: "keys/baowang.pub"
   global_sudo: "on"
   sudo_password: "baowang2015"           
   logfile: "logs/rex.log"
   groups_file: "true,config/ip_lists.ini"
   timeout: "10"
   max_connect_retries: "8"
   parallelism: "5"
   table: "pre_host_zzb_dev"
   monitor_table: "pre_bwzzbmonitor_dev"
   rerite_info_table: "false"
   default_jsonfile: "cache/json/json.txt"
   table_string: "id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir"
   softdir: "softdir/"
   configuredir: "configuredir/"
   local_prodir: "remotecomdir/softdir/"
   local_confdir: "remotecomdir/configuredir/"
   temp: "temp/"
   download_dir: "download/"
   log_rsync_server: "172.16.0.244"
   log_rsync_user: "logupload"
   log_rsync_pass: "cm12016"
   log_rsync_module: "logupload"
   max_grep_row: 500
   backup_dir: "/data/backup"
   baseapp_dir: "/data/www/apps"
   download_all : "false"
   is_link :  "true"
   is_stop :  "false"
   is_start :  "true"
   download_record_log: "logs/download_record.log"
   deploy_config_table: "pre_server_detail"
   deploy_record_table: "pre_deploy_manage"
   deploy_status_table: "pre_deploy_status"
   external_status: "false"
   external_deploy_config_table: "pre_external_server_detail"
   list_all_task_status: "false"
   list_task: "check,list,run,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Deploy:Db:initdb,Deploy:Core:syncpro,Common:Use:download,Common:Use:run,Common:Use:upload,logCenter:main:liveLog,logCenter:main:lookLog,logCenter:main:getLog,logCenter:main:queryList,logCenter:main:grepLog"
   service_start_retry: "5"
   rsync_log_stdout: "false"
#新框架生产环境配置文件
 com:
   key_auth: "true"
   pass_auth: "false"  
   user: "baowang"
   password: ""
   private_key: "keys/baowang"
   public_key: "keys/baowang.pub"
   global_sudo: "on"
   sudo_password: "baowang2015"           
   logfile: "logs/rex.log"
   groups_file: "true,config/ip_lists.ini"
   timeout: "10"
   max_connect_retries: "8"
   parallelism: "5"
   table: "pre_host_zzb_dev"
   monitor_table: "pre_bwzzbmonitor_dev"
   rerite_info_table: "false"
   default_jsonfile: "/Users/huanggaoming/Project/RexCenter/cache/json/json.txt"
   table_string: "id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir"
   softdir: "/data/RexDeploy/softdir/"
   configuredir: "/data/RexDeploy/configuredir/"
   local_prodir: "/data/RexDeploy/remotecomdir/softdir/"
   local_confdir: "/data/RexDeploy/remotecomdir/configuredir/"
   temp: "/data/RexDeploy/temp/"
   download_dir: "download/"
   log_rsync_server: "172.16.0.244"
   log_rsync_user: "logupload"
   log_rsync_pass: "cm12016"
   log_rsync_module: "logupload"
   backup_dir: "/data/backup"
   baseapp_dir: "/data/www/apps"
   download_all : "false"
   is_link :  "true"
   is_stop :  "false"
   is_start :  "true"
   download_record_log: "/data/RexDeploy/logs/download_record.log"
   deploy_config_table: "pre_server_detail"
   deploy_record_table: "pre_deploy_manage"
   deploy_status_table: "pre_deploy_status"
   external_status: "false"
   external_deploy_config_table: "pre_external_server_detail"
   list_all_task_status: "false"
   list_task: "check,list,run,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Deploy:Db:initdb,Common:Use:download,Common:Use:run,Common:Use:upload,Deploy:Core:syncpro"
   service_start_retry: "5"
   rsync_log_stdout: "true"
