---
dev:
  allow_env: uat,prod
  backup_dir: /data/backup
  baseapp_dir: /data/www/apps
  checkurl_init_time: '10'
  checkurl_interval_time: '10'
  checkurl_max_count: '5'
  checkurl_respoon_print: '0'
  common_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpWHGBki+1TBbqC7bH7yX8Q6GQpJ+oVuuH+W0fQknwHOMQi717ejsngDpLWdvNvGdGEt4TmuJ0cLUN3EOibIrn04B/7nY1Pm04KgvVsWT4QwQaGR/pYqjo+pQKZB9Sd2kiqDVFp4urG6COqERZ0dlUMwH4Hi+hVWra9Z23tPSbKt/0TV9QI0DFwgWB0dbZPW6xQt/Q4lalR0hWaHQ+oCs3kAjd/A5qM4LYMVqpUGo8Q4oYBZktorTWEu92wBpe0WAfigxElUkog/ZwOhmJ7l/B5HV+tzcDnHv0Qy730QaPChQ1Pvu77Cq4kbWV/DFt5bUbrUci6yWSlQ3CiVKOHnf'
  configuredir: configuredir/
  cos_upload_shell: scripts/cos_upload.sh
  dbhost: 127.0.0.1
  dbname: autotask
  dbpassword: root
  dbport: '3306'
  dbuser: root
  default_basehttp: http://192.168.1.102/data/Group/public/home
  default_basehttp2: http://192.168.1.228
  default_download_env: uat
  default_jsonfile: cache/json/json.txt
  deploy_config_table: pre_server_detail
  deploy_finish_file: /tmp/deploy_finish_file.txt
  deploy_interval_time: '60'
  deploy_max_count: '60'
  deploy_record_table: pre_deploy_manage
  deploy_status_table: pre_deploy_status
  download_all: 'false'
  download_dir: download/
  download_method: rsync
  download_record_log: logs/download_record.log
  envDesc: 本地开发环境
  external_deploy_config_table: pre_external_server_detail
  external_status: 'false'
  finish_qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  global_sudo: off
  groups_file: true,config/ip_lists.ini
  httpdowndir: download/http
  is_check_dir: '1'
  is_download_process_status: '0'
  is_link: 'true'
  is_qq: '1'
  is_start: 'true'
  is_stop: 'false'
  is_weight_allow: '1'
  is_weixin: '0'
  key_auth: 'false'
  list_all_task_status: 'false'
  list_task: check,list,run,deploy,release,rollback,service,download,upload,checkurl,queryk,updatek,getLog,grepLog,lookLog,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Enter:route:downloadCombile,Enter:deploy:main,Deploy:Db:initdb,Deploy:Core:syncpro,Deploy:Core:diff,Deploy:Configure:config,logCenter:main:liveLog,logCenter:main:lookLog,logCenter:main:getLog,logCenter:main:queryList,logCenter:main:grepLog,User:main:route,loadService:main:query,loadService:main:queryk,loadService:main:update,loadService:main:check,Common:Use:download,Common:Use:run,Common:Use:upload,Common:Use:post,Common:Use:get,Predeploy:Judge:accesslog,Cos:Upload:txy
  local_confdir: remotecomdir/configuredir/
  local_prodir: remotecomdir/softdir/
  log_rsync_module: logupload
  log_rsync_pass: logupload12016
  log_rsync_server: 127.0.0.1
  log_rsync_user: logupload
  logfile: logs/rex.log
  max_connect_retries: '8'
  max_grep_row: '500'
  max_sleep_time: '5'
  max_weight_count: '8'
  monitor_table: pre_bwzzbmonitor_dev
  parallelism: '10'
  pass_auth: 'true'
  password: autotask2015
  private_key: keys/autotask
  public_key: keys/autotask.pub
  qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  random_temp_file: /tmp/random_temp.txt
  rerite_info_table: 'false'
  rsync_log_stdout: 'false'
  savetmpDir: /tmp
  service_start_retry: '5'
  softdir: softdir/
  sudo_password: ''
  table: pre_host_zzb_dev
  table_load_key: load_key_sorts
  table_string: id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir
  temp: temp/
  timeout: '10'
  update_local_confdir: updatedir/configuredir/
  update_local_prodir: updatedir/softdir/
  upload_method: rsync
  user: root
  weixin_config: '{"url": "http://127.0.0.1:7180/Autops/web/wxapi?party=1","header": "","params": "","require":"","requirecode":"200"}'
env:
  key: dev
prod:
  allow_env: uat,prod
  backup_dir: /data/backup
  baseapp_dir: /data/www/apps
  checkurl_init_time: '10'
  checkurl_interval_time: '10'
  checkurl_max_count: '5'
  checkurl_respoon_print: '0'
  common_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpWHGBki+1TBbqC7bH7yX8Q6GQpJ+oVuuH+W0fQknwHOMQi717ejsngDpLWdvNvGdGEt4TmuJ0cLUN3EOibIrn04B/7nY1Pm04KgvVsWT4QwQaGR/pYqjo+pQKZB9Sd2kiqDVFp4urG6COqERZ0dlUMwH4Hi+hVWra9Z23tPSbKt/0TV9QI0DFwgWB0dbZPW6xQt/Q4lalR0hWaHQ+oCs3kAjd/A5qM4LYMVqpUGo8Q4oYBZktorTWEu92wBpe0WAfigxElUkog/ZwOhmJ7l/B5HV+tzcDnHv0Qy730QaPChQ1Pvu77Cq4kbWV/DFt5bUbrUci6yWSlQ3CiVKOHnf'
  configuredir: configuredir/
  cos_upload_shell: scripts/cos_upload.sh
  dbhost: 127.0.0.1
  dbname: autotask
  dbpassword: root
  dbport: '3306'
  dbuser: root
  default_basehttp: http://192.168.1.102/data/Group/public/home
  default_basehttp2: http://192.168.1.228
  default_download_env: uat
  default_jsonfile: cache/json/json.txt
  deploy_config_table: pre_server_detail
  deploy_finish_file: /tmp/deploy_finish_file.txt
  deploy_interval_time: '60'
  deploy_max_count: '60'
  deploy_record_table: pre_deploy_manage
  deploy_status_table: pre_deploy_status
  download_all: 'false'
  download_dir: download/
  download_method: rsync
  download_record_log: logs/download_record.log
  envDesc: 生产环境
  external_deploy_config_table: pre_external_server_detail
  external_status: 'false'
  finish_qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  global_sudo: off
  groups_file: true,config/ip_lists.ini
  httpdowndir: download/http
  is_check_dir: '1'
  is_download_process_status: '0'
  is_link: 'true'
  is_qq: '1'
  is_start: 'true'
  is_stop: 'false'
  is_weight_allow: '1'
  is_weixin: '0'
  key_auth: 'false'
  list_all_task_status: 'false'
  list_task: check,list,run,deploy,release,rollback,service,download,upload,checkurl,queryk,updatek,getLog,grepLog,lookLog,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Enter:route:downloadCombile,Enter:deploy:main,Deploy:Db:initdb,Deploy:Core:syncpro,Deploy:Core:diff,Deploy:Configure:config,logCenter:main:liveLog,logCenter:main:lookLog,logCenter:main:getLog,logCenter:main:queryList,logCenter:main:grepLog,User:main:route,loadService:main:query,loadService:main:queryk,loadService:main:update,loadService:main:check,Common:Use:download,Common:Use:run,Common:Use:upload,Common:Use:post,Common:Use:get,Predeploy:Judge:accesslog,Cos:Upload:txy
  local_confdir: remotecomdir/configuredir/
  local_prodir: remotecomdir/softdir/
  log_rsync_module: logupload
  log_rsync_pass: logupload12016
  log_rsync_server: 127.0.0.1
  log_rsync_user: logupload
  logfile: logs/rex.log
  max_connect_retries: '8'
  max_grep_row: '500'
  max_sleep_time: '5'
  max_weight_count: '8'
  monitor_table: pre_bwzzbmonitor_dev
  parallelism: '10'
  pass_auth: 'true'
  password: autotask2015
  private_key: keys/autotask
  public_key: keys/autotask.pub
  qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  random_temp_file: /tmp/random_temp.txt
  rerite_info_table: 'false'
  rsync_log_stdout: 'false'
  savetmpDir: /tmp
  service_start_retry: '5'
  softdir: softdir/
  sudo_password: ''
  table: pre_host_zzb_dev
  table_load_key: load_key_sorts
  table_string: id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir
  temp: temp/
  timeout: '10'
  update_local_confdir: updatedir/configuredir/
  update_local_prodir: updatedir/softdir/
  upload_method: rsync
  user: root
  weixin_config: '{"url": "http://127.0.0.1:7180/Autops/web/wxapi?party=1","header": "","params": "","require":"","requirecode":"200"}'
test:
  allow_env: uat,prod
  backup_dir: /data/backup
  baseapp_dir: /data/www/apps
  checkurl_init_time: '10'
  checkurl_interval_time: '10'
  checkurl_max_count: '5'
  checkurl_respoon_print: '0'
  common_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpWHGBki+1TBbqC7bH7yX8Q6GQpJ+oVuuH+W0fQknwHOMQi717ejsngDpLWdvNvGdGEt4TmuJ0cLUN3EOibIrn04B/7nY1Pm04KgvVsWT4QwQaGR/pYqjo+pQKZB9Sd2kiqDVFp4urG6COqERZ0dlUMwH4Hi+hVWra9Z23tPSbKt/0TV9QI0DFwgWB0dbZPW6xQt/Q4lalR0hWaHQ+oCs3kAjd/A5qM4LYMVqpUGo8Q4oYBZktorTWEu92wBpe0WAfigxElUkog/ZwOhmJ7l/B5HV+tzcDnHv0Qy730QaPChQ1Pvu77Cq4kbWV/DFt5bUbrUci6yWSlQ3CiVKOHnf'
  configuredir: configuredir/
  cos_upload_shell: scripts/cos_upload.sh
  dbhost: 127.0.0.1
  dbname: autotask
  dbpassword: root
  dbport: '3306'
  dbuser: root
  default_basehttp: http://192.168.1.102/data/Group/public/home
  default_basehttp2: http://192.168.1.228
  default_download_env: uat
  default_jsonfile: cache/json/json.txt
  deploy_config_table: pre_server_detail
  deploy_finish_file: /tmp/deploy_finish_file.txt
  deploy_interval_time: '60'
  deploy_max_count: '60'
  deploy_record_table: pre_deploy_manage
  deploy_status_table: pre_deploy_status
  download_all: 'false'
  download_dir: download/
  download_method: rsync
  download_record_log: logs/download_record.log
  envDesc: 测试环境
  external_deploy_config_table: pre_external_server_detail
  external_status: 'false'
  finish_qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  global_sudo: off
  groups_file: true,config/ip_lists.ini
  httpdowndir: download/http
  is_check_dir: '1'
  is_download_process_status: '0'
  is_link: 'true'
  is_qq: '1'
  is_start: 'true'
  is_stop: 'false'
  is_weight_allow: '1'
  is_weixin: '0'
  key_auth: 'false'
  list_all_task_status: 'false'
  list_task: check,list,run,deploy,release,rollback,service,download,upload,checkurl,queryk,updatek,getLog,grepLog,lookLog,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Enter:route:downloadCombile,Enter:deploy:main,Deploy:Db:initdb,Deploy:Core:syncpro,Deploy:Core:diff,Deploy:Configure:config,logCenter:main:liveLog,logCenter:main:lookLog,logCenter:main:getLog,logCenter:main:queryList,logCenter:main:grepLog,User:main:route,loadService:main:query,loadService:main:queryk,loadService:main:update,loadService:main:check,Common:Use:download,Common:Use:run,Common:Use:upload,Common:Use:post,Common:Use:get,Predeploy:Judge:accesslog,Cos:Upload:txy
  local_confdir: remotecomdir/configuredir/
  local_prodir: remotecomdir/softdir/
  log_rsync_module: logupload
  log_rsync_pass: logupload12016
  log_rsync_server: 127.0.0.1
  log_rsync_user: logupload
  logfile: logs/rex.log
  max_connect_retries: '8'
  max_grep_row: '500'
  max_sleep_time: '5'
  max_weight_count: '8'
  monitor_table: pre_bwzzbmonitor_dev
  parallelism: '10'
  pass_auth: 'true'
  password: autotask2015
  private_key: keys/autotask
  public_key: keys/autotask.pub
  qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  random_temp_file: /tmp/random_temp.txt
  rerite_info_table: 'false'
  rsync_log_stdout: 'false'
  savetmpDir: /tmp
  service_start_retry: '5'
  softdir: softdir/
  sudo_password: ''
  table: pre_host_zzb_dev
  table_load_key: load_key_sorts
  table_string: id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir
  temp: temp/
  timeout: '10'
  update_local_confdir: updatedir/configuredir/
  update_local_prodir: updatedir/softdir/
  upload_method: rsync
  user: root
  weixin_config: '{"url": "http://127.0.0.1:7180/Autops/web/wxapi?party=1","header": "","params": "","require":"","requirecode":"200"}'
testsection: {}
uat:
  allow_env: uat,prod
  backup_dir: /data/backup
  baseapp_dir: /data/www/apps
  checkurl_init_time: '10'
  checkurl_interval_time: '10'
  checkurl_max_count: '5'
  checkurl_respoon_print: '0'
  common_public_key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHpWHGBki+1TBbqC7bH7yX8Q6GQpJ+oVuuH+W0fQknwHOMQi717ejsngDpLWdvNvGdGEt4TmuJ0cLUN3EOibIrn04B/7nY1Pm04KgvVsWT4QwQaGR/pYqjo+pQKZB9Sd2kiqDVFp4urG6COqERZ0dlUMwH4Hi+hVWra9Z23tPSbKt/0TV9QI0DFwgWB0dbZPW6xQt/Q4lalR0hWaHQ+oCs3kAjd/A5qM4LYMVqpUGo8Q4oYBZktorTWEu92wBpe0WAfigxElUkog/ZwOhmJ7l/B5HV+tzcDnHv0Qy730QaPChQ1Pvu77Cq4kbWV/DFt5bUbrUci6yWSlQ3CiVKOHnf'
  configuredir: configuredir/
  cos_upload_shell: scripts/cos_upload.sh
  dbhost: 127.0.0.1
  dbname: autotask
  dbpassword: root
  dbport: '3306'
  dbuser: root
  default_basehttp: http://192.168.1.102/data/Group/public/home
  default_basehttp2: http://192.168.1.228
  default_download_env: uat
  default_jsonfile: cache/json/json.txt
  deploy_config_table: pre_server_detail
  deploy_finish_file: /tmp/deploy_finish_file.txt
  deploy_interval_time: '60'
  deploy_max_count: '60'
  deploy_record_table: pre_deploy_manage
  deploy_status_table: pre_deploy_status
  download_all: 'false'
  download_dir: download/
  download_method: rsync
  download_record_log: logs/download_record.log
  envDesc: 预生产环境
  external_deploy_config_table: pre_external_server_detail
  external_status: 'false'
  finish_qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  global_sudo: off
  groups_file: true,config/ip_lists.ini
  httpdowndir: download/http
  is_check_dir: '1'
  is_download_process_status: '0'
  is_link: 'true'
  is_qq: '1'
  is_start: 'true'
  is_stop: 'false'
  is_weight_allow: '1'
  is_weixin: '0'
  key_auth: 'false'
  list_all_task_status: 'false'
  list_task: check,list,run,deploy,release,rollback,service,download,upload,checkurl,queryk,updatek,getLog,grepLog,lookLog,Enter:route:deploy,Enter:route:download,Enter:route:rollback,Enter:route:service,Enter:route:downloadCombile,Enter:deploy:main,Deploy:Db:initdb,Deploy:Core:syncpro,Deploy:Core:diff,Deploy:Configure:config,logCenter:main:liveLog,logCenter:main:lookLog,logCenter:main:getLog,logCenter:main:queryList,logCenter:main:grepLog,User:main:route,loadService:main:query,loadService:main:queryk,loadService:main:update,loadService:main:check,Common:Use:download,Common:Use:run,Common:Use:upload,Common:Use:post,Common:Use:get,Predeploy:Judge:accesslog,Cos:Upload:txy
  local_confdir: remotecomdir/configuredir/
  local_prodir: remotecomdir/softdir/
  log_rsync_module: logupload
  log_rsync_pass: logupload12016
  log_rsync_server: 127.0.0.1
  log_rsync_user: logupload
  logfile: logs/rex.log
  max_connect_retries: '8'
  max_grep_row: '500'
  max_sleep_time: '5'
  max_weight_count: '8'
  monitor_table: pre_bwzzbmonitor_dev
  parallelism: '10'
  pass_auth: 'true'
  password: autotask2015
  private_key: keys/autotask
  public_key: keys/autotask.pub
  qq_config: '{"url": "http://127.0.0.1:15700/send_private_msg?user_id=530035210","header": "","params": "","require":"message_id","requirecode":"200"}'
  random_temp_file: /tmp/random_temp.txt
  rerite_info_table: 'false'
  rsync_log_stdout: 'false'
  savetmpDir: /tmp
  service_start_retry: '5'
  softdir: softdir/
  sudo_password: ''
  table: pre_host_zzb_dev
  table_load_key: load_key_sorts
  table_string: id,app_key,server_name,network_ip,pro_type,config_dir,pro_dir,pro_key,pro_init,local_name,is_deloy_dir
  temp: temp/
  timeout: '10'
  update_local_confdir: updatedir/configuredir/
  update_local_prodir: updatedir/softdir/
  upload_method: rsync
  user: root
  weixin_config: '{"url": "http://127.0.0.1:7180/Autops/web/wxapi?party=1","header": "","params": "","require":"","requirecode":"200"}'
